### ISSUE TITLE
Version error when running program 

### ISSUE THREAD

**Issue by bhargavd6** [inukshuk/anystyle-parser#32]
Hi I am individual 

and trying to use this library for my research work... i tried to build it from source and running but gettting below error.. and parser is not working ... please provide detailed usage:

[root@localhost lib]# ls
anystyle  sample.rb
[root@localhost lib]# ruby sample.rb 
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- anystyle/parser/version (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/workspace/anystyle-parser/lib/anystyle/parser.rb:9:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sample.rb:2:in `<main>'
[root@localhost lib]# pwd
/root/workspace/anystyle-parser/lib
[root@localhost lib]# 

my sample program is as below to invoke the parser .. please advise if i am missing anything.

I am running this program from anystyle-parser/lib/sample.rb program.

please suggest if i am missing ..

[root@localhost lib]# cat sample.rb 
#!/usr/local/bin/ruby
require './anystyle/parser'

Anystyle.parse 'Poe, Edgar A. Essays and Reviews. New York: Library of America, 1984.'

puts $b

puts "Bye"

I tried as suggested in the web site but none of them working to invoke the parser...

[root@localhost lib]# 

Thanks in Advance

**Comment by bhargavd6** [comment]
Thanks for quick replies and appriciated efforts for reading long mails and trying to help. It is working chamngly .. please close this bug
