### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by xjsachs** [inukshuk/anystyle-parser#41]
We’re getting a segmentation fault when training the parser with our own data. Our training set is 167 lines. When we leave the default model out of the training, Anystyle doesn’t complain:

1.9.3-p551 :002 > Anystyle.parser.train 'train.txt', true
 => #<Wapiti::Model:0x000000012cb6a8> 

However, when we do include the default model …

- - -
1.9.3-p551 :002 > Anystyle.parser.train 'train.txt', false
/home/jsachs/.rvm/gems/ruby-1.9.3-p551/gems/wapiti-0.1.1/lib/wapiti/model.rb:54: [BUG] Segmentation fault
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0026 p:---- s:0096 b:0096 l:000095 d:000095 CFUNC  :train
c:0025 p:0079 s:0092 b:0092 l:000091 d:000091 METHOD /home/jsachs/.rvm/gems/ruby-1.9.3-p551/gems/wapiti-0.1.1/lib/wapiti/model.rb:54
c:0024 p:0102 s:0087 b:0087 l:000086 d:000086 METHOD /home/jsachs/.rvm/gems/ruby-1.9.3-p551/gems/anystyle-parser-0.7.4/lib/anystyle/parser/parser.rb:161
c:0023 p:0025 s:0082 b:0082 l:000278 d:000081 EVAL   (irb):2
c:0022 p:---- s:0080 b:0080 l:000079 d:000079 FINISH
c:0021 p:---- s:0078 b:0078 l:000077 d:000077 CFUNC  :eval
c:0020 p:0028 s:0071 b:0071 l:000070 d:000070 METHOD /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/workspace.rb:80
c:0019 p:0033 s:0064 b:0063 l:000062 d:000062 METHOD /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/context.rb:254
c:0018 p:0031 s:0058 b:0058 l:0001e8 d:000057 BLOCK  /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:159
c:0017 p:0042 s:0050 b:0050 l:000049 d:000049 METHOD /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:273
c:0016 p:0011 s:0045 b:0045 l:0001e8 d:000044 BLOCK  /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:156
c:0015 p:0144 s:0041 b:0041 l:000024 d:000040 BLOCK  /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:243
c:0014 p:---- s:0038 b:0038 l:000037 d:000037 FINISH
c:0013 p:---- s:0036 b:0036 l:000035 d:000035 CFUNC  :loop
c:0012 p:0009 s:0033 b:0033 l:000024 d:000032 BLOCK  /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:229
c:0011 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0010 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC  :catch
c:0009 p:0023 s:0025 b:0025 l:000024 d:000024 METHOD /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:228
c:0008 p:0046 s:0022 b:0022 l:0001e8 d:0001e8 METHOD /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:155
c:0007 p:0011 s:0019 b:0019 l:001368 d:000018 BLOCK  /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:70
c:0006 p:---- s:0017 b:0017 l:000016 d:000016 FINISH
c:0005 p:---- s:0015 b:0015 l:000014 d:000014 CFUNC  :catch
c:0004 p:0183 s:0011 b:0011 l:001368 d:001368 METHOD /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:69
c:0003 p:0039 s:0006 b:0006 l:000388 d:0024e8 EVAL   /home/jsachs/.rvm/rubies/ruby-1.9.3-p551/bin/irb:12
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:000388 d:000388 TOP   

-- Ruby level backtrace information ----------------------------------------
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:69:in `start'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:69:in `catch'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:70:in `block in start'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb.rb:159:in `block (2 levels) in eval_input'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/context.rb:254:in `evaluate'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/workspace.rb:80:in `evaluate'
/home/jsachs/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/irb/workspace.rb:80:in `eval'
(irb):2:in `irb_binding'
/home/jsachs/.rvm/gems/ruby-1.9.3-p551/gems/anystyle-parser-0.7.4/lib/anystyle/parser/parser.rb:161:in `train'
/home/jsachs/.rvm/gems/ruby-1.9.3-p551/gems/wapiti-0.1.1/lib/wapiti/model.rb:54:in `train'
/home/jsachs/.rvm/gems/ruby-1.9.3-p551/gems/wapiti-0.1.1/lib/wapiti/model.rb:54:in `train'

-- C level backtrace information -------------------------------------------
SEGV received in SEGV handler
Aborted
- - -

We’re getting this on three different platforms - OS X, Debian, and Ubuntu. This is without Kyoto-cabinet or Redis installed.

**Comment by xjsachs** [comment]
Duplicate of Issue 40
